Repository 2025-MJU-SW-CONTEST/SW_FE, pull requests merged in 2025-08, with the labels that each got.

#8 [Feat/#7] 온보딩-로그인 페이지 구현
  src/assets/icon/BackIcon.jsx
  src/assets/icon/KakaoIcon.jsx
  src/components/common/BackButton.jsx
  src/components/common/BottomNavigationItem.jsx
  src/components/common/Button.jsx
  src/components/login/KakaoLoginButton.jsx
  src/components/onboarding/PageIndicator.jsx
  src/index.css
  src/locales/ko/onboarding.json
  src/pages/Login.jsx
  src/pages/OAuthCallback.jsx
  src/pages/Onboarding.jsx
  src/routes/pagePath.js
  src/routes/routes.jsx
  src/utils/formatText.jsx
Labels: ✨ Feat, 💄 Style, 🔨 Refactor

#10 [Feat/#6] AI 해설사 화면 구현
  package.json
  src/assets/icon/CancelIcon.jsx
  src/assets/icon/CheckIcon.jsx
  src/assets/icon/SendIcon.jsx
  src/components/AIChat/AppBar.jsx
  src/components/AIChat/ImageButton.jsx
  src/components/AIChat/Input.jsx
  src/components/common/BottomNavigationItem.jsx
  src/components/common/ChatBubble.jsx
  src/components/common/ChatList.jsx
  src/index.css
  src/layout/ProtectedRoute.jsx
  src/layout/RootLayout.jsx
  src/locales/ko/placeholder.json
  src/pages/AIChat.jsx
  yarn.lock
Labels: ✨ Feat

#12 [Style/#9] 마이페이지 제작
  package.json
  src/assets/icon/KebabMenuIcon.jsx
  src/assets/icon/MyPage/MyIcon_1.jsx
  src/assets/icon/MyPage/MyIcon_2.jsx
  src/assets/icon/MyPage/MyIcon_3.jsx
  src/assets/icon/MyPage/MyIcon_4.jsx
  src/assets/icon/MyPage/MyIcon_5.jsx
  src/assets/icon/MyPage/NextIcon.jsx
  src/components/common/BackHeader.jsx
  src/components/common/DeleteButton.jsx
  src/components/common/EditButton.jsx
  src/components/common/KebabMenu.jsx
  src/components/common/ToastMessage.jsx
  src/components/interpretation.jsx/ContentBody.jsx
  src/components/interpretation.jsx/HashtagList.jsx
  src/components/interpretation.jsx/InterpretationCard.jsx
  src/components/interpretation.jsx/ProfileInfo.jsx
  src/components/mypage/ConfirmModal.jsx
  src/components/mypage/MyProfile.jsx
  src/components/mypage/MypageButtons.jsx
  src/index.css
  src/locales/i18n/index.js
  src/locales/ko/backheader.json
  src/locales/ko/button.json
  src/locales/ko/description.json
  src/locales/ko/list.json
  src/pages/EditInterpretation.jsx
  src/pages/MyInterpretations.jsx
  src/pages/MyNicknameChange.jsx
  src/pages/Mypage.jsx
  src/pages/OAuthCallback.jsx
  src/routes/pagePath.js
  src/routes/routes.jsx
  src/store/useAuth.js
  yarn.lock
Labels: ✨ Feat, 💄 Style

#16 [Style/#11]: 회원가입 추가 디자인 사항 반영
  src/assets/icon/CancelGradientIcon.jsx
  src/assets/icon/ExclamationIcon.jsx
  src/components/common/Button.jsx
  src/components/common/TextField.jsx
  src/locales/ko/description.json
  src/pages/Register.jsx
Labels: ✨ Feat, 💄 Style

#18 [Style/#17] AI해설사 피그마 변경사항 반영
  src/assets/icon/FillyIcon.jsx
  src/components/AIChat/AppBar.jsx
  src/components/common/ChatBubble.jsx
  src/pages/AIChat.jsx
Labels: 💄 Style

#21 [Feat/#15]
  public/img/test.png
  src/assets/icon/ChatIcon.jsx
  src/assets/icon/ExclamationIcon.jsx
  src/assets/icon/Home/PlusIcon.jsx
  src/assets/icon/Home/SearchBarIcon.jsx
  src/assets/icon/Home/SearchClearIcon.jsx
  src/assets/icon/Home/SearchIcon.jsx
  src/assets/icon/Home/StarIcon.jsx
  src/assets/icon/Home/XIcon.jsx
  src/components/common/AddButton.jsx
  src/components/common/BackHeader.jsx
  src/components/home/CastList.jsx
  src/components/home/ChatButton.jsx
  src/components/home/InterpretationInput.jsx
  src/components/home/MovieCard.jsx
  src/components/home/MovieInterpretationTab.jsx
  src/components/home/MoviePoster.jsx
  src/components/home/MovieRating.jsx
  src/components/home/MovieSearch.jsx
  src/components/home/MovieTitle.jsx
  src/components/home/Synopsis.jsx
  src/components/home/TabMenu.jsx
  src/components/interpretation.jsx/HashtagList.jsx
  src/components/interpretation.jsx/InterpretationCard.jsx
  src/locales/ko/button.json
  src/locales/ko/description.json
  src/locales/ko/placeholder.json
  src/locales/ko/title.json
  src/pages/CreateInterpretation.jsx
  src/pages/EditInterpretation.jsx
  src/pages/Home.jsx
  src/pages/Login.jsx
  src/pages/MovieDetailPage.jsx
  src/pages/MyInterpretations.jsx
  src/pages/MyNicknameChange.jsx
  src/pages/Mypage.jsx
  src/pages/Onboarding.jsx
  src/routes/pagePath.js
  src/routes/routes.jsx
Labels: ✨ Feat, 💄 Style

#38 [Feat/#37] 해석 관련 API 연동 완료
  src/apis/analysisService.js
  src/components/common/BackHeader.jsx
  src/components/common/KebabMenu.jsx
  src/components/common/ToastMessage.jsx
  src/components/home/InterpretationInput.jsx
  src/components/home/MovieInterpretationTab.jsx
  src/components/interpretation.jsx/HashtagList.jsx
  src/components/interpretation.jsx/InterpretationCard.jsx
  src/components/interpretation.jsx/ProfileInfo.jsx
  src/locales/ko/description.json
  src/locales/ko/popup.json
  src/pages/CreateInterpretation.jsx
  src/pages/EditInterpretation.jsx
  src/pages/Home.jsx
  src/pages/MovieDetailPage.jsx
  src/pages/MyInterpretations.jsx
  src/pages/OAuthCallback.jsx
Labels: ✨ Feat, 🔨 Refactor
